

input_images: /path/to/images
horizontal_process: False  # Is true to run the pipeline horizontally (one image at a time: Obj Detec -> OCR -> NER)
object_detection: True  # Is true to run object detection, else searches for object detection results in the input_images folder to run OCR
ocr: True  # Is true to run OCR, else searches for OCR results in the input_images folder to run NER
